import type { Metadata } from 'next';

import DefaultLayout from '../components/layout/layout';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Neodog',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
